standards: [SBTi, RE100, "GHG Protocol", ICVCM, CORSIA, ISO 14001, Pacto Global]
solutions: [mrv, offsets, tokenization, electrification, agrivoltaics, biogas, hydrogen, heat_pumps, reforestation]
roles: [Chief Sustainability Officer, ESG Manager, Climate Analyst]