mappings:
  - pattern: "(?i)oil|petro|gas|hidrocarb|upstream|downstream"
    to: "oil_gas"
  - pattern: "(?i)energy|energ[ií]a|eléctr|electric|power|solar|fotovoltaic|e[oó]lic|wind|hidroel[eé]ctric|geoterm|renew|bioenerg|biofuel"
    to: "energy_power"
  - pattern: "(?i)mining|min[ií]er|minería|minera"
    to: "mining_metals"
  - pattern: "(?i)chem|qu[ií]m|material|siderurg|metalúrg|fertiliz|plástic|petroqu[ií]m|pol[ií]mer"
    to: "chemicals_materials"
  - pattern: "(?i)manufact|fábric|industrial|automotriz|automotive|textil|maquil|ensambl"
    to: "manufacturing"
  - pattern: "(?i)construct|construcci[oó]n|real estate|inmobili|infraestruct|desarroll|viviend|obra"
    to: "construction_realestate"
  - pattern: "(?i)transport|logist|ferro|a[eé]re|aero|aviaci|metro|naval|shipping|turism|turíst|portu|mar[ií]t|aerol[ií]n"
    to: "transport_logistics"
  - pattern: "(?i)agri|agro|food|alimento|lácteo|bev|cervec|brew|helad|c[aá]fe|cacao|ganad|harin|az[ií]car"
    to: "agro_food"
  - pattern: "(?i)retail|consumer|consumo|comercio|minoris|tienda|supermerc|farmac|ferreter|cosm[eé]t|perfume|hogar|departamental|e-?commerce"
    to: "retail_consumer"
  - pattern: "(?i)water|waste|residu|circular|h[ií]dric|saneam|sanit|alcantarill|tratamiento"
    to: "water_waste_circularity"
  - pattern: "(?i)finance|bank|banca|financ|insur|seguro|holding|banco|fond[oa]|inversion|burs[aá]til|cooperativ|microfin"
    to: "finance_insurance"
  - pattern: "(?i)ict|telecom|telefon|software|internet|tech|tecnolog|medios|cine|animaci|televis|notici|audiovisual|videojueg|stream|rad[ií]o|digital|m[oó]vil"
    to: "ict_telecom"
