greenhouse:
  - slug: "enel"
    company_domain: "enel.com"
  - slug: "aes"
    company_domain: "aes.com"
lever:
  - slug: "globant"
    company_domain: "globant.com"
  - slug: "10pearls"
    company_domain: "10pearls.com"
