include:
  - climate
  - renewable
  - solar
  - wind
  - hidrogeno
  - battery
  - efficiency
  - emissions
  - carbono
  - adaptacion
  - resiliencia
  - economia circular
  - recicl
  - biodiver
  - electrico
  - movilidad electrica
  - vehiculo electrico
  - heat pump
  - geothermal
  - storage
exclude:
  - pronostico
  - meteorologia
  - weather
  - tormenta
  - lluvia
  - nevadas
  - temperatura
  - show de tv
  - programa de tv
  - reality show
  - futbol
  - malware
  - ciberataque
  - ciberseguridad
  - gratis
  - turismo
