include:
  - climate
  - climate action
  - climate initiative
  - net zero
  - cero neto
  - carbono neutral
  - science based targets
  - renewable
  - solar
  - wind
  - hidrogeno verde
  - hydrogen
  - battery
  - eficiencia energetica
  - efficiency
  - emissions reduction
  - reducción de emisiones
  - carbono
  - captura de carbono
  - adaptacion
  - resiliencia climatica
  - economia circular
  - reciclar
  - biodiver
  - electrificacion
  - electrico
  - movilidad electrica
  - vehiculo electrico
  - heat pump
  - geothermal
  - storage
exclude:
  - pronostico
  - meteorologia
  - weather
  - tormenta
  - lluvia
  - nevadas
  - temperatura
  - show de tv
  - programa de tv
  - reality show
  - futbol
  - malware
  - ciberataque
  - ciberseguridad
  - gratis
  - turismo
