providers:
  gdelt:
    enabled: true
    days: 7
    max_records: 250
  rss:
    enabled: true
    feeds:
      - https://news.google.com/rss/search?q=climate+tech
      - https://feeds.arstechnica.com/arstechnica/technology-lab
    limit_per_feed: 30
  google_news:
    enabled: true
    language: es
    region: AR
    limit_per_company: 5
