providers:
  gdelt:
    enabled: true
    days: 14
    max_records: 75
  rss:
    enabled: true
    feeds:
    - https://news.google.com/rss/search?q=climate+tech
    - https://feeds.arstechnica.com/arstechnica/technology-lab
    limit_per_feed: 20
  google_news:
    enabled: true
    language: es
    region: AR
    limit_per_company: 3
