sample:
  total_target: 1200
  min_per_stratum: 20
  countries:
  - AR
  - BR
  - CL
  - CO
  - MX
  - PE
  - UY
  industries:
  - energy_power
  - oil_gas
  - mining_metals
  - chemicals_materials
  - manufacturing
  - construction_realestate
  - transport_logistics
  - agro_food
  - retail_consumer
  - water_waste_circularity
  - finance_insurance
  - ict_telecom
  min_employees_options:
  - 100
  - 250
