countries: [MX, BR, CO, CL, AR, UY]

industries:
  - energy_power
  - oil_gas
  - mining_metals
  - chemicals_materials
  - manufacturing
  - construction_realestate
  - transport_logistics
  - agro_food
  - retail_consumer
  - water_waste_circularity
  - finance_insurance
  - ict_telecom

size_bins:
- {name: s, min: 50, max: 249}
- {name: m, min: 250, max: 999}
- {name: l, min: 1000, max: null}
window_months: 12
hot_days: 90

sample:
  total_target: 1200        # sugerencia actual
  min_per_stratum: 20       # piso por estrato que definas
  stratify_by: ["country","industry"]
  seed: 42